# Dockerfile for Protocol Buffer code generation
FROM golang:1.25-alpine

# Install protobuf compiler and tools
RUN apk add --no-cache protobuf protobuf-dev

# Install Go protobuf plugins
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /workspace

# This container will be used to generate proto files
CMD ["protoc", "--version"]