// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: proto/datahub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from Source to Hub
type SourceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SourceMessage_Registration
	//	*SourceMessage_QueryResult
	//	*SourceMessage_HealthStatus
	//	*SourceMessage_Error
	Message       isSourceMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceMessage) Reset() {
	*x = SourceMessage{}
	mi := &file_proto_datahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMessage) ProtoMessage() {}

func (x *SourceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMessage.ProtoReflect.Descriptor instead.
func (*SourceMessage) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{0}
}

func (x *SourceMessage) GetMessage() isSourceMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SourceMessage) GetRegistration() *SourceRegistration {
	if x != nil {
		if x, ok := x.Message.(*SourceMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *SourceMessage) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Message.(*SourceMessage_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *SourceMessage) GetHealthStatus() *HealthStatus {
	if x != nil {
		if x, ok := x.Message.(*SourceMessage_HealthStatus); ok {
			return x.HealthStatus
		}
	}
	return nil
}

func (x *SourceMessage) GetError() *SourceError {
	if x != nil {
		if x, ok := x.Message.(*SourceMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSourceMessage_Message interface {
	isSourceMessage_Message()
}

type SourceMessage_Registration struct {
	Registration *SourceRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type SourceMessage_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,2,opt,name=query_result,json=queryResult,proto3,oneof"`
}

type SourceMessage_HealthStatus struct {
	HealthStatus *HealthStatus `protobuf:"bytes,3,opt,name=health_status,json=healthStatus,proto3,oneof"`
}

type SourceMessage_Error struct {
	Error *SourceError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SourceMessage_Registration) isSourceMessage_Message() {}

func (*SourceMessage_QueryResult) isSourceMessage_Message() {}

func (*SourceMessage_HealthStatus) isSourceMessage_Message() {}

func (*SourceMessage_Error) isSourceMessage_Message() {}

// Messages from Hub to Source
type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HubMessage_RegistrationAck
	//	*HubMessage_QueryExecution
	//	*HubMessage_HealthCheck
	Message       isHubMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_proto_datahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{1}
}

func (x *HubMessage) GetMessage() isHubMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HubMessage) GetRegistrationAck() *RegistrationAck {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_RegistrationAck); ok {
			return x.RegistrationAck
		}
	}
	return nil
}

func (x *HubMessage) GetQueryExecution() *QueryExecution {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_QueryExecution); ok {
			return x.QueryExecution
		}
	}
	return nil
}

func (x *HubMessage) GetHealthCheck() *HealthCheckRequest {
	if x != nil {
		if x, ok := x.Message.(*HubMessage_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

type isHubMessage_Message interface {
	isHubMessage_Message()
}

type HubMessage_RegistrationAck struct {
	RegistrationAck *RegistrationAck `protobuf:"bytes,1,opt,name=registration_ack,json=registrationAck,proto3,oneof"`
}

type HubMessage_QueryExecution struct {
	QueryExecution *QueryExecution `protobuf:"bytes,2,opt,name=query_execution,json=queryExecution,proto3,oneof"`
}

type HubMessage_HealthCheck struct {
	HealthCheck *HealthCheckRequest `protobuf:"bytes,3,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

func (*HubMessage_RegistrationAck) isHubMessage_Message() {}

func (*HubMessage_QueryExecution) isHubMessage_Message() {}

func (*HubMessage_HealthCheck) isHubMessage_Message() {}

// Source Registration
type SourceRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // Unique source identifier
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                          // Category for round-robin
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                      // API version
	AuthToken     string                 `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Authentication token
	Operations    []*Operation           `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`                // Supported operations
	Capabilities  *SourceCapabilities    `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`            // Optional capabilities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRegistration) Reset() {
	*x = SourceRegistration{}
	mi := &file_proto_datahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRegistration) ProtoMessage() {}

func (x *SourceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRegistration.ProtoReflect.Descriptor instead.
func (*SourceRegistration) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{2}
}

func (x *SourceRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceRegistration) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SourceRegistration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SourceRegistration) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *SourceRegistration) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *SourceRegistration) GetCapabilities() *SourceCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Operation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                            // Operation identifier
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                              // Human-readable description
	InputSchema    *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`           // JSON Schema for input
	OutputSchema   *structpb.Struct       `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`        // JSON Schema for output
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Operation timeout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_datahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{3}
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Operation) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *Operation) GetOutputSchema() *structpb.Struct {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *Operation) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SourceCapabilities struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrentQueries int32                  `protobuf:"varint,1,opt,name=max_concurrent_queries,json=maxConcurrentQueries,proto3" json:"max_concurrent_queries,omitempty"`
	SupportsTransactions bool                   `protobuf:"varint,2,opt,name=supports_transactions,json=supportsTransactions,proto3" json:"supports_transactions,omitempty"`
	SupportsBatchQueries bool                   `protobuf:"varint,3,opt,name=supports_batch_queries,json=supportsBatchQueries,proto3" json:"supports_batch_queries,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SourceCapabilities) Reset() {
	*x = SourceCapabilities{}
	mi := &file_proto_datahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceCapabilities) ProtoMessage() {}

func (x *SourceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceCapabilities.ProtoReflect.Descriptor instead.
func (*SourceCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{4}
}

func (x *SourceCapabilities) GetMaxConcurrentQueries() int32 {
	if x != nil {
		return x.MaxConcurrentQueries
	}
	return 0
}

func (x *SourceCapabilities) GetSupportsTransactions() bool {
	if x != nil {
		return x.SupportsTransactions
	}
	return false
}

func (x *SourceCapabilities) GetSupportsBatchQueries() bool {
	if x != nil {
		return x.SupportsBatchQueries
	}
	return false
}

type RegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId    string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"` // Hub-assigned connection ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_proto_datahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationAck) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

// Query Execution
type QueryExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"` // Unique query identifier
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`            // Operation to execute
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`          // Query parameters
	Metadata      *QueryMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`              // Query metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExecution) Reset() {
	*x = QueryExecution{}
	mi := &file_proto_datahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExecution) ProtoMessage() {}

func (x *QueryExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExecution.ProtoReflect.Descriptor instead.
func (*QueryExecution) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{6}
}

func (x *QueryExecution) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryExecution) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *QueryExecution) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueryExecution) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueryResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QueryId         string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data            *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                 // Result data
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`             // Error if success=false
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"` // Query execution time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_proto_datahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{7}
}

func (x *QueryResult) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *QueryResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_datahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Metrics       *SourceMetrics         `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_datahub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{9}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *HealthStatus) GetMetrics() *SourceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SourceMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections int32                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	QueriesProcessed  int32                  `protobuf:"varint,2,opt,name=queries_processed,json=queriesProcessed,proto3" json:"queries_processed,omitempty"`
	AvgResponseTimeMs float64                `protobuf:"fixed64,3,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SourceMetrics) Reset() {
	*x = SourceMetrics{}
	mi := &file_proto_datahub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMetrics) ProtoMessage() {}

func (x *SourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMetrics.ProtoReflect.Descriptor instead.
func (*SourceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{10}
}

func (x *SourceMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SourceMetrics) GetQueriesProcessed() int32 {
	if x != nil {
		return x.QueriesProcessed
	}
	return 0
}

func (x *SourceMetrics) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *SourceMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type SourceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceError) Reset() {
	*x = SourceError{}
	mi := &file_proto_datahub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceError) ProtoMessage() {}

func (x *SourceError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceError.ProtoReflect.Descriptor instead.
func (*SourceError) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{11}
}

func (x *SourceError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SourceError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SourceError) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExposerName   string                 `protobuf:"bytes,1,opt,name=exposer_name,json=exposerName,proto3" json:"exposer_name,omitempty"` // Exposer identifier
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`       // Exposer auth token
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`                                // Target data label
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`                        // Operation to execute
	Parameters    *structpb.Struct       `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`                      // Query parameters
	Metadata      *QueryMetadata         `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`                          // Query metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_datahub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{12}
}

func (x *QueryRequest) GetExposerName() string {
	if x != nil {
		return x.ExposerName
	}
	return ""
}

func (x *QueryRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *QueryRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QueryRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *QueryRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueryRequest) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Response data
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Trace         *QueryTrace            `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"` // Execution trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_datahub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{13}
}

func (x *QueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *QueryResponse) GetTrace() *QueryTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type QueryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`    // Unique query ID
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Optional client identifier
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional headers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_proto_datahub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{14}
}

func (x *QueryMetadata) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *QueryMetadata) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type QueryTrace struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceName        string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"` // Which source handled it
	HubProcessingMs   int64                  `protobuf:"varint,2,opt,name=hub_processing_ms,json=hubProcessingMs,proto3" json:"hub_processing_ms,omitempty"`
	SourceExecutionMs int64                  `protobuf:"varint,3,opt,name=source_execution_ms,json=sourceExecutionMs,proto3" json:"source_execution_ms,omitempty"`
	TotalTimeMs       int64                  `protobuf:"varint,4,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	TracePoints       []string               `protobuf:"bytes,5,rep,name=trace_points,json=tracePoints,proto3" json:"trace_points,omitempty"` // Debug trace points
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryTrace) Reset() {
	*x = QueryTrace{}
	mi := &file_proto_datahub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTrace) ProtoMessage() {}

func (x *QueryTrace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datahub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTrace.ProtoReflect.Descriptor instead.
func (*QueryTrace) Descriptor() ([]byte, []int) {
	return file_proto_datahub_proto_rawDescGZIP(), []int{15}
}

func (x *QueryTrace) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *QueryTrace) GetHubProcessingMs() int64 {
	if x != nil {
		return x.HubProcessingMs
	}
	return 0
}

func (x *QueryTrace) GetSourceExecutionMs() int64 {
	if x != nil {
		return x.SourceExecutionMs
	}
	return 0
}

func (x *QueryTrace) GetTotalTimeMs() int64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *QueryTrace) GetTracePoints() []string {
	if x != nil {
		return x.TracePoints
	}
	return nil
}

var File_proto_datahub_proto protoreflect.FileDescriptor

const file_proto_datahub_proto_rawDesc = "" +
	"\n" +
	"\x13proto/datahub.proto\x12\adatahub\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x02\n" +
	"\rSourceMessage\x12A\n" +
	"\fregistration\x18\x01 \x01(\v2\x1b.datahub.SourceRegistrationH\x00R\fregistration\x129\n" +
	"\fquery_result\x18\x02 \x01(\v2\x14.datahub.QueryResultH\x00R\vqueryResult\x12<\n" +
	"\rhealth_status\x18\x03 \x01(\v2\x15.datahub.HealthStatusH\x00R\fhealthStatus\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x14.datahub.SourceErrorH\x00R\x05errorB\t\n" +
	"\amessage\"\xe4\x01\n" +
	"\n" +
	"HubMessage\x12E\n" +
	"\x10registration_ack\x18\x01 \x01(\v2\x18.datahub.RegistrationAckH\x00R\x0fregistrationAck\x12B\n" +
	"\x0fquery_execution\x18\x02 \x01(\v2\x17.datahub.QueryExecutionH\x00R\x0equeryExecution\x12@\n" +
	"\fhealth_check\x18\x03 \x01(\v2\x1b.datahub.HealthCheckRequestH\x00R\vhealthCheckB\t\n" +
	"\amessage\"\xec\x01\n" +
	"\x12SourceRegistration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\x122\n" +
	"\n" +
	"operations\x18\x05 \x03(\v2\x12.datahub.OperationR\n" +
	"operations\x12?\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1b.datahub.SourceCapabilitiesR\fcapabilities\"\xe4\x01\n" +
	"\tOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12<\n" +
	"\routput_schema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\foutputSchema\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\xb5\x01\n" +
	"\x12SourceCapabilities\x124\n" +
	"\x16max_concurrent_queries\x18\x01 \x01(\x05R\x14maxConcurrentQueries\x123\n" +
	"\x15supports_transactions\x18\x02 \x01(\bR\x14supportsTransactions\x124\n" +
	"\x16supports_batch_queries\x18\x03 \x01(\bR\x14supportsBatchQueries\"f\n" +
	"\x0fRegistrationAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\"\xb6\x01\n" +
	"\x0eQueryExecution\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x122\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.datahub.QueryMetadataR\bmetadata\"\xc0\x01\n" +
	"\vQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"N\n" +
	"\x12HealthCheckRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x81\x01\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x120\n" +
	"\ametrics\x18\x03 \x01(\v2\x16.datahub.SourceMetricsR\ametrics\"\xc3\x01\n" +
	"\rSourceMetrics\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x05R\x11activeConnections\x12+\n" +
	"\x11queries_processed\x18\x02 \x01(\x05R\x10queriesProcessed\x12/\n" +
	"\x14avg_response_time_ms\x18\x03 \x01(\x01R\x11avgResponseTimeMs\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x8b\x01\n" +
	"\vSourceError\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf1\x01\n" +
	"\fQueryRequest\x12!\n" +
	"\fexposer_name\x18\x01 \x01(\tR\vexposerName\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x127\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x122\n" +
	"\bmetadata\x18\x06 \x01(\v2\x16.datahub.QueryMetadataR\bmetadata\"\xc1\x01\n" +
	"\rQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12)\n" +
	"\x05trace\x18\x05 \x01(\v2\x13.datahub.QueryTraceR\x05trace\"\xfc\x01\n" +
	"\rQueryMetadata\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\aheaders\x18\x04 \x03(\v2#.datahub.QueryMetadata.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\n" +
	"QueryTrace\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12*\n" +
	"\x11hub_processing_ms\x18\x02 \x01(\x03R\x0fhubProcessingMs\x12.\n" +
	"\x13source_execution_ms\x18\x03 \x01(\x03R\x11sourceExecutionMs\x12\"\n" +
	"\rtotal_time_ms\x18\x04 \x01(\x03R\vtotalTimeMs\x12!\n" +
	"\ftrace_points\x18\x05 \x03(\tR\vtracePoints2\x8a\x01\n" +
	"\aDataHub\x12@\n" +
	"\rConnectSource\x12\x16.datahub.SourceMessage\x1a\x13.datahub.HubMessage(\x010\x01\x12=\n" +
	"\fExecuteQuery\x12\x15.datahub.QueryRequest\x1a\x16.datahub.QueryResponseB/Z-github.com/regentmarkets/agents-datahub/protob\x06proto3"

var (
	file_proto_datahub_proto_rawDescOnce sync.Once
	file_proto_datahub_proto_rawDescData []byte
)

func file_proto_datahub_proto_rawDescGZIP() []byte {
	file_proto_datahub_proto_rawDescOnce.Do(func() {
		file_proto_datahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datahub_proto_rawDesc), len(file_proto_datahub_proto_rawDesc)))
	})
	return file_proto_datahub_proto_rawDescData
}

var file_proto_datahub_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_datahub_proto_goTypes = []any{
	(*SourceMessage)(nil),         // 0: datahub.SourceMessage
	(*HubMessage)(nil),            // 1: datahub.HubMessage
	(*SourceRegistration)(nil),    // 2: datahub.SourceRegistration
	(*Operation)(nil),             // 3: datahub.Operation
	(*SourceCapabilities)(nil),    // 4: datahub.SourceCapabilities
	(*RegistrationAck)(nil),       // 5: datahub.RegistrationAck
	(*QueryExecution)(nil),        // 6: datahub.QueryExecution
	(*QueryResult)(nil),           // 7: datahub.QueryResult
	(*HealthCheckRequest)(nil),    // 8: datahub.HealthCheckRequest
	(*HealthStatus)(nil),          // 9: datahub.HealthStatus
	(*SourceMetrics)(nil),         // 10: datahub.SourceMetrics
	(*SourceError)(nil),           // 11: datahub.SourceError
	(*QueryRequest)(nil),          // 12: datahub.QueryRequest
	(*QueryResponse)(nil),         // 13: datahub.QueryResponse
	(*QueryMetadata)(nil),         // 14: datahub.QueryMetadata
	(*QueryTrace)(nil),            // 15: datahub.QueryTrace
	nil,                           // 16: datahub.QueryMetadata.HeadersEntry
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_proto_datahub_proto_depIdxs = []int32{
	2,  // 0: datahub.SourceMessage.registration:type_name -> datahub.SourceRegistration
	7,  // 1: datahub.SourceMessage.query_result:type_name -> datahub.QueryResult
	9,  // 2: datahub.SourceMessage.health_status:type_name -> datahub.HealthStatus
	11, // 3: datahub.SourceMessage.error:type_name -> datahub.SourceError
	5,  // 4: datahub.HubMessage.registration_ack:type_name -> datahub.RegistrationAck
	6,  // 5: datahub.HubMessage.query_execution:type_name -> datahub.QueryExecution
	8,  // 6: datahub.HubMessage.health_check:type_name -> datahub.HealthCheckRequest
	3,  // 7: datahub.SourceRegistration.operations:type_name -> datahub.Operation
	4,  // 8: datahub.SourceRegistration.capabilities:type_name -> datahub.SourceCapabilities
	17, // 9: datahub.Operation.input_schema:type_name -> google.protobuf.Struct
	17, // 10: datahub.Operation.output_schema:type_name -> google.protobuf.Struct
	17, // 11: datahub.QueryExecution.parameters:type_name -> google.protobuf.Struct
	14, // 12: datahub.QueryExecution.metadata:type_name -> datahub.QueryMetadata
	17, // 13: datahub.QueryResult.data:type_name -> google.protobuf.Struct
	18, // 14: datahub.HealthCheckRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 15: datahub.HealthStatus.metrics:type_name -> datahub.SourceMetrics
	18, // 16: datahub.SourceError.timestamp:type_name -> google.protobuf.Timestamp
	17, // 17: datahub.QueryRequest.parameters:type_name -> google.protobuf.Struct
	14, // 18: datahub.QueryRequest.metadata:type_name -> datahub.QueryMetadata
	17, // 19: datahub.QueryResponse.data:type_name -> google.protobuf.Struct
	15, // 20: datahub.QueryResponse.trace:type_name -> datahub.QueryTrace
	18, // 21: datahub.QueryMetadata.timestamp:type_name -> google.protobuf.Timestamp
	16, // 22: datahub.QueryMetadata.headers:type_name -> datahub.QueryMetadata.HeadersEntry
	0,  // 23: datahub.DataHub.ConnectSource:input_type -> datahub.SourceMessage
	12, // 24: datahub.DataHub.ExecuteQuery:input_type -> datahub.QueryRequest
	1,  // 25: datahub.DataHub.ConnectSource:output_type -> datahub.HubMessage
	13, // 26: datahub.DataHub.ExecuteQuery:output_type -> datahub.QueryResponse
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_datahub_proto_init() }
func file_proto_datahub_proto_init() {
	if File_proto_datahub_proto != nil {
		return
	}
	file_proto_datahub_proto_msgTypes[0].OneofWrappers = []any{
		(*SourceMessage_Registration)(nil),
		(*SourceMessage_QueryResult)(nil),
		(*SourceMessage_HealthStatus)(nil),
		(*SourceMessage_Error)(nil),
	}
	file_proto_datahub_proto_msgTypes[1].OneofWrappers = []any{
		(*HubMessage_RegistrationAck)(nil),
		(*HubMessage_QueryExecution)(nil),
		(*HubMessage_HealthCheck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datahub_proto_rawDesc), len(file_proto_datahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datahub_proto_goTypes,
		DependencyIndexes: file_proto_datahub_proto_depIdxs,
		MessageInfos:      file_proto_datahub_proto_msgTypes,
	}.Build()
	File_proto_datahub_proto = out.File
	file_proto_datahub_proto_goTypes = nil
	file_proto_datahub_proto_depIdxs = nil
}
