// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/datahub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataHub_ConnectSource_FullMethodName = "/datahub.DataHub/ConnectSource"
	DataHub_ExecuteQuery_FullMethodName  = "/datahub.DataHub/ExecuteQuery"
)

// DataHubClient is the client API for DataHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataHubClient interface {
	// Bidirectional streaming for source connection
	ConnectSource(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SourceMessage, HubMessage], error)
	// HTTP/2 endpoint for exposer queries
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type dataHubClient struct {
	cc grpc.ClientConnInterface
}

func NewDataHubClient(cc grpc.ClientConnInterface) DataHubClient {
	return &dataHubClient{cc}
}

func (c *dataHubClient) ConnectSource(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SourceMessage, HubMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataHub_ServiceDesc.Streams[0], DataHub_ConnectSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SourceMessage, HubMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataHub_ConnectSourceClient = grpc.BidiStreamingClient[SourceMessage, HubMessage]

func (c *dataHubClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, DataHub_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataHubServer is the server API for DataHub service.
// All implementations must embed UnimplementedDataHubServer
// for forward compatibility.
type DataHubServer interface {
	// Bidirectional streaming for source connection
	ConnectSource(grpc.BidiStreamingServer[SourceMessage, HubMessage]) error
	// HTTP/2 endpoint for exposer queries
	ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedDataHubServer()
}

// UnimplementedDataHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataHubServer struct{}

func (UnimplementedDataHubServer) ConnectSource(grpc.BidiStreamingServer[SourceMessage, HubMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ConnectSource not implemented")
}
func (UnimplementedDataHubServer) ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedDataHubServer) mustEmbedUnimplementedDataHubServer() {}
func (UnimplementedDataHubServer) testEmbeddedByValue()                 {}

// UnsafeDataHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataHubServer will
// result in compilation errors.
type UnsafeDataHubServer interface {
	mustEmbedUnimplementedDataHubServer()
}

func RegisterDataHubServer(s grpc.ServiceRegistrar, srv DataHubServer) {
	// If the following call pancis, it indicates UnimplementedDataHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataHub_ServiceDesc, srv)
}

func _DataHub_ConnectSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataHubServer).ConnectSource(&grpc.GenericServerStream[SourceMessage, HubMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataHub_ConnectSourceServer = grpc.BidiStreamingServer[SourceMessage, HubMessage]

func _DataHub_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataHubServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataHub_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataHubServer).ExecuteQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataHub_ServiceDesc is the grpc.ServiceDesc for DataHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datahub.DataHub",
	HandlerType: (*DataHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _DataHub_ExecuteQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectSource",
			Handler:       _DataHub_ConnectSource_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/datahub.proto",
}
