apiVersion: v1
kind: Service
metadata:
  name: exposer
  namespace: datahub-exposer
  labels:
    app: datahub-exposer
    component: exposer
spec:
  type: ClusterIP
  selector:
    app: datahub-exposer
    component: exposer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: exposer-external
  namespace: datahub-exposer
  labels:
    app: datahub-exposer
    component: exposer
spec:
  type: LoadBalancer
  selector:
    app: datahub-exposer
    component: exposer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP